[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://reqgenai-server.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://reqgenai-server.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://reqgenai-server.onrender.com"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://reqgenai-server.onrender.com"
