services:
  - type: web
    name: reqgenai-server
    env: node
    plan: free
    rootDir: server
    nodeRuntime: 20
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://reqgenai-frontend.netlify.app
      - key: N8N_REQUIREMENT_EXTRACTION_URL
        sync: false
      - key: N8N_BRD_GENERATION_URL
        sync: false
      - key: N8N_REQUIREMENT_BLUEPRINT_URL
        sync: false
      - key: BITRIX24_BASE_URL
        sync: false
      - key: BITRIX24_WEBHOOK_URL
        sync: false
      - key: BITRIX24_PROJECT_WEBHOOK_URL
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        sync: false
